#Only show paper doll when in first-person mode.
#Default Value: true
first_person_only = true
#Set axis the player head can move on.
#Default Value: YAW
#Allowed Values: YAW, PITCH, BOTH
head_movement = "BOTH"
#Define a screen corner to align the paper doll display to.
#Default Value: TOP_LEFT
#Allowed Values: TOP_LEFT, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_RIGHT
position = "TOP_RIGHT"
#Display paper doll while performing these actions.
#Default Value: [paperdoll:sprinting, paperdoll:swimming, paperdoll:crawling, paperdoll:crouching, paperdoll:flying, paperdoll:gliding]
#Allowed Values: paperdoll:sprinting, paperdoll:swimming, paperdoll:crawling, paperdoll:crouching, paperdoll:flying, paperdoll:gliding, paperdoll:riding, paperdoll:spin_attacking, paperdoll:using
display_actions = ["paperdoll:sprinting", "paperdoll:swimming", "paperdoll:crawling", "paperdoll:crouching", "paperdoll:flying", "paperdoll:gliding"]
#Scale of paper doll. Also affected by video settings gui scale.
#Default Value: 4
#Range: 1 ~ 24
scale = 4
#Offset on y-axis from original doll position.
#Default Value: 0
#Range: > -2147483648
offset_y = 0
#Amount of ticks the paper doll will be kept on screen after its display conditions are no longer met. Set to 0 to always display the doll.
#Default Value: 15
#Range: > 0
display_time = 0
#Offset on x-axis from original doll position.
#Default Value: 0
#Range: > -2147483648
offset_x = 0
#Shift paper doll downwards when it would otherwise overlap with potion icons while showing in the top screen right corner.
#Default Value: true
potion_shift = true
