name = "1.21 Optimized"
author = "Splack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0832ae60b52d8d8e75c74ecb352ba66f777efb0221618b294e7ab1fe87d37e0c"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
