name = "1.21 Optimized"
author = "Splack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0358c63531aa4319e8ed48cee65861bc0e652a59c7a2ba4e63e6bb873e4dd87a"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
