name = "1.21 Optimized"
author = "Splack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ba9b747250cb337e98b6dda2f934b1393beadb6e5bb10ac85443ef642ad3e27"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
