name = "1.21 Optimized"
author = "Splack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2bf470a2cea6bcfbdd4e269f7989f6ac76de09b80669379dbdca55b74185973"

[versions]
fabric = "0.16.13"
minecraft = "1.21.4"
